// <auto-generated />
using System;
using FintrackAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FintrackAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311200019_CreateDataBaseWithBigint")]
    partial class CreateDataBaseWithBigint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FintrackAPI.Models.Categoria", b =>
                {
                    b.Property<long>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cat_id_categoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CategoriaId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cat_ds_descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cat_nm_nome");

                    b.HasKey("CategoriaId");

                    b.ToTable("CAT_categoria");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1000000001L,
                            Descricao = "Supermercado, padaria, restaurantes",
                            Nome = "Alimentação"
                        },
                        new
                        {
                            CategoriaId = 1000000002L,
                            Descricao = "Ônibus, metrô, combustível, apps de transporte",
                            Nome = "Transporte"
                        },
                        new
                        {
                            CategoriaId = 1000000003L,
                            Descricao = "Recebimento mensal da empresa",
                            Nome = "Salário"
                        });
                });

            modelBuilder.Entity("FintrackAPI.Models.TipoTransacao", b =>
                {
                    b.Property<long>("TipoTransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tpt_id_tipo_transacao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TipoTransacaoId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("tpt_ds_descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tpt_nm_nome");

                    b.HasKey("TipoTransacaoId");

                    b.ToTable("TPT_tipo_transacao");

                    b.HasData(
                        new
                        {
                            TipoTransacaoId = 1000000001L,
                            Descricao = "Saídas de dinheiro e pagamentos",
                            Nome = "Despesa"
                        },
                        new
                        {
                            TipoTransacaoId = 1000000002L,
                            Descricao = "Entradas de dinheiro e ganhos",
                            Nome = "Receita"
                        },
                        new
                        {
                            TipoTransacaoId = 1000000003L,
                            Descricao = "Movimentação entre contas",
                            Nome = "Transferência"
                        });
                });

            modelBuilder.Entity("FintrackAPI.Models.Transacao", b =>
                {
                    b.Property<long>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tra_id_transacao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("TransacaoId"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("tra_id_categoria");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("tra_dt_data");

                    b.Property<bool>("IsCredito")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tra_fl_credito");

                    b.Property<bool>("IsRecorrente")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tra_fl_recorrente");

                    b.Property<long>("TipoTransacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tra_id_tipo_transacao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tra_nm_titulo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tra_vl_valor");

                    b.HasKey("TransacaoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TipoTransacaoId");

                    b.ToTable("TRA_transacao");

                    b.HasData(
                        new
                        {
                            TransacaoId = 1000000001L,
                            CategoriaId = 1000000001L,
                            Data = new DateOnly(2026, 3, 5),
                            IsCredito = true,
                            IsRecorrente = false,
                            TipoTransacaoId = 1000000001L,
                            Titulo = "Compra no Supermercado",
                            Valor = 350.75m
                        },
                        new
                        {
                            TransacaoId = 1000000002L,
                            CategoriaId = 1000000003L,
                            Data = new DateOnly(2026, 3, 1),
                            IsCredito = false,
                            IsRecorrente = true,
                            TipoTransacaoId = 1000000002L,
                            Titulo = "Pagamento Mensal",
                            Valor = 5000.00m
                        });
                });

            modelBuilder.Entity("FintrackAPI.Models.Transacao", b =>
                {
                    b.HasOne("FintrackAPI.Models.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FintrackAPI.Models.TipoTransacao", "TipoTransacao")
                        .WithMany("Transacoes")
                        .HasForeignKey("TipoTransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("TipoTransacao");
                });

            modelBuilder.Entity("FintrackAPI.Models.Categoria", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FintrackAPI.Models.TipoTransacao", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
